java_library(
    name = "keys",
    srcs = glob(["*.java"]),
        visibility = ["//visibility:public"],
        deps = ["//ax.xz.wireguard.noise/src/main/java/ax/xz/wireguard/noise/crypto/internal"]
)
