java_library(
    name = "crypto",
    srcs = glob(["*.java"]),
    deps = ["//ax.xz.wireguard.noise/src/main/java/ax/xz/wireguard/noise/crypto/internal"],
    visibility = ["//visibility:public"],
)
