java_binary(
    name = "ax.xz.wireguard.noise",
    srcs = ["module-info.java"],
    deps = [
    	"//ax.xz.wireguard.noise/src/main/java/ax/xz/wireguard/noise/crypto",
    	"//ax.xz.wireguard.noise/src/main/java/ax/xz/wireguard/noise/keys",
    	"//ax.xz.wireguard.noise/src/main/java/ax/xz/wireguard/noise/handshake"
    ],
)