java_library(
    name = "handshake",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
    	"//ax.xz.wireguard.noise/src/main/java/ax/xz/wireguard/noise/crypto",
    	"//ax.xz.wireguard.noise/src/main/java/ax/xz/wireguard/noise/keys"
   	]
)
