version: "3.7"

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        restart: unless-stopped
        networks:
            - wireguard-network
    wireguard-server:
        build: .
        volumes:
            - ./server.conf:/wireguard.conf
            - ./entrypoint_server.sh:/entrypoint_routing.sh
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
        networks:
            - wireguard-network
        devices:
            - /dev/net/tun:/dev/net/tun
    wireguard-client:
        build: .
        volumes:
            - ./client.conf:/wireguard.conf
            - ./entrypoint_client.sh:/entrypoint_routing.sh
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
        networks:
            - wireguard-network
        devices:
            - /dev/net/tun:/dev/net/tun


networks:
    wireguard-network:
        driver: bridge