version: '3.7'

services:
    wireguard-server:
        build: ..
        entrypoint: "/entrypoint_routing.sh"
        volumes:
            - ./server.conf:/wireguard.conf
            - ./entrypoint_server.sh:/entrypoint_routing.sh
            - ./profiling:/profiling
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        restart: unless-stopped
        networks:
            - wireguard-network
        security_opt:
            - seccomp:unconfined
        devices:
            - /dev/net/tun:/dev/net/tun
        command:
            - -agentpath:/libasyncProfiler.so=start,event=wall,cpu,alloc,file=/profiling/profile-server.jfr,interval=1000000,timeout=20

    iperf3-server:
        image: networkstatic/iperf3
        command: -s
        depends_on:
            - wireguard-server
            - wireguard-client
        networks:
            - wireguard-network

    wireguard-client:
        build: ..
        entrypoint: "/entrypoint_routing.sh"
        volumes:
            - ./client.conf:/wireguard.conf
            - ./entrypoint_client.sh:/entrypoint_routing.sh
            - ./profiling:/profiling
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        restart: unless-stopped
        networks:
            - wireguard-network
        security_opt:
            - seccomp:unconfined
        devices:
            - /dev/net/tun:/dev/net/tun
        command:
            - -agentpath:/libasyncProfiler.so=start,event=wall,cpu,alloc,file=/profiling/profile-client.jfr,interval=1000000,timeout=20
    wireguard-client-iperf3:
        image: networkstatic/iperf3
        command: -c iperf3-server -t 120 -P 1 -u -b 1G
        network_mode: "service:wireguard-client"
        depends_on:
            - wireguard-client
            - iperf3-server

networks:
    wireguard-network:
        driver: bridge