version: "3.7"

services:
    wireguard-server:
        build: .
        volumes:
            - ./server.conf:/wireguard.conf
            - ./entrypoint_server.sh:/entrypoint_routing.sh
            - ./profiling:/profiling
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        restart: unless-stopped
        networks:
            - wireguard-network
        security_opt:
            - seccomp:unconfined
        devices:
            - /dev/net/tun:/dev/net/tun

        command:
            - -agentpath:/libasyncProfiler.so=start,alluser,event=cpu,event=alloc,event=lock,file=/profiling/profile.jfr,interval=100000,timeout=60

    iperf3-server:
        image: networkstatic/iperf3
        command: -s
        depends_on:
            - wireguard-server
        networks:
            - wireguard-network


    wireguard-client:
        build: .
        volumes:
            - ./client.conf:/wireguard.conf
            - ./entrypoint_client.sh:/entrypoint_routing.sh
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        restart: unless-stopped
        networks:
            - wireguard-network
        security_opt:
            - seccomp:unconfined
        devices:
            - /dev/net/tun:/dev/net/tun

    wireguard-client-iperf3:
        image: networkstatic/iperf3
        command: -c iperf3-server -t 120 -P 16
        network_mode: "service:wireguard-client"
        depends_on:
            - wireguard-client
            - iperf3-server


networks:
    wireguard-network:
        driver: bridge